version: '3'
services:
  api:
    build: .
    ports:
      - 3003:3003
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      PORT: ${PORT}
      TOKEN: ${TOKEN}
    volumes:
      - ./:/app
    depends_on:
      - database
  database:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306